version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: 2do-db
    environment:
      POSTGRES_DB: 2do
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54320:5432"
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
